### ISSUE TITLE
in python

### ISSUE THREAD

**Issue by lefuturiste** [Ollie-Boyd/Linkedin-post-timestamp-extractor#1]
Thanks for making this script. Now I think there is a way to use bitwise manipulation instead of strings but that's a little bit less compréhensible.
```python
def datetime_from_id(id: int):
    epoch = (id & 0xffffffffff800000) >> 22
    return datetime.utcfromtimestamp(epoch/1000)
```

**Comment by Ollie-Boyd** [comment]
Thanks for that, hopefully someone might find it interesting!
