### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by Hexstream** [Ollie-Boyd/Linkedin-post-timestamp-extractor#3]
It's great that the tool extracts the native UTC time, but this leaves users scrambling for a timezone converter that doesn't suck. I haven't found one.

It would be really great if there was built-in support for _also_ displaying the date in a chosen timezone.

I realize this would take some development effort...

**edit:** There could just be a way of selecting a timezone offset as an integer...

**Comment by DGrothe-PhD** [comment]
I had about the same idea. 
Currently time is displayed as UTC while for Germany it's +2h (still quite close)

It's just easy to implement, going to commit my fix in the next days.

**Comment by DGrothe-PhD** [comment]
See PR #9

**Comment by Hexstream** [comment]
This works great, thank you!!
