### ISSUE TITLE
Regex issue with linkedin URL

### ISSUE THREAD

**Issue by gpenessot** [Ollie-Boyd/Linkedin-post-timestamp-extractor#7]
Hello @Ollie-Boyd 

Thanks for this code, very useful !
I had some issues with re pattern, here's the proposed change :

Change pattern : 'activity-(\d+)' is not valid and causes "Invalid Linkedin ID" error for every URL. 'activity:( \d+)' returns correct timestamp

**Comment by Ollie-Boyd** [comment]
Hi Gael, 
Thanks for your feedback. 
Ah OK. Feel free to send a PR if you have a moment and I'll merge it. 
Cheers, 
Ollie

**Comment by DGrothe-PhD** [comment]
Looks like it's done and can be closed.
